import { readFile, writeFile } from "fs/promises";
import { NextRequest, NextResponse } from "next/server";
import path from "path";

// Define all configuration variables
interface ConfigData {
  shopify: {
    storeDomain: string;
    storefrontAccessToken: string;
    webhookSecret: string;
    revalidationSecret: string;
    publicUrl: string;
    adminAccessToken: string;
    clientId: string;
    clientSecret: string;
  };
  site: {
    companyName: string;
    siteName: string;
  };
  notifications: {
    enableEmail: boolean;
    enableWhatsApp: boolean;
    adminEmail: string;
    customMessage: string;
  };
  emailService: {
    provider: string;
    apiKey: string;
    fromEmail: string;
    fromName: string;
  };
  whatsappService: {
    provider: string;
    apiKey: string;
    phoneNumber: string;
    publicPhoneNumber: string;
  };
  collections: {
    maxCollections: number;
    cacheTime: string;
  };
  newsletter: {
    service: string;
    apiKey: string;
    listId: string;
  };
  payment: {
    provider: string;
  };
}

export async function GET() {
  try {
    // Read current .env file
    const envPath = path.join(process.cwd(), ".env");
    const envContent = await readFile(envPath, "utf-8");
    
    // Parse environment variables
    const config: ConfigData = {
      shopify: {
        storeDomain: getEnvValue(envContent, "SHOPIFY_STORE_DOMAIN", ""),
        storefrontAccessToken: getEnvValue(envContent, "SHOPIFY_STOREFRONT_ACCESS_TOKEN", ""),
        webhookSecret: getEnvValue(envContent, "SHOPIFY_WEBHOOK_SECRET", ""),
        revalidationSecret: getEnvValue(envContent, "SHOPIFY_REVALIDATION_SECRET", ""),
        publicUrl: getEnvValue(envContent, "NEXT_PUBLIC_URL", ""),
        adminAccessToken: getEnvValue(envContent, "SHOPIFY_ADMIN_ACCESS_TOKEN", ""),
        clientId: getEnvValue(envContent, "SHOPIFY_CLIENT_ID", ""),
        clientSecret: getEnvValue(envContent, "SHOPIFY_CLIENT_SECRET", ""),
      },
      site: {
        companyName: getEnvValue(envContent, "COMPANY_NAME", ""),
        siteName: getEnvValue(envContent, "SITE_NAME", ""),
      },
      notifications: {
        enableEmail: getEnvValue(envContent, "ENABLE_EMAIL_NOTIFICATIONS", "false") === "true",
        enableWhatsApp: getEnvValue(envContent, "ENABLE_WHATSAPP_NOTIFICATIONS", "false") === "true",
        adminEmail: getEnvValue(envContent, "ADMIN_EMAIL", ""),
        customMessage: getEnvValue(envContent, "CUSTOM_ORDER_MESSAGE", ""),
      },
      emailService: {
        provider: getEnvValue(envContent, "EMAIL_SERVICE_PROVIDER", "sendgrid"),
        apiKey: getEnvValue(envContent, "EMAIL_SERVICE_API_KEY", ""),
        fromEmail: getEnvValue(envContent, "EMAIL_FROM_EMAIL", ""),
        fromName: getEnvValue(envContent, "EMAIL_FROM_NAME", ""),
      },
      whatsappService: {
        provider: getEnvValue(envContent, "WHATSAPP_SERVICE_PROVIDER", "callmebot"),
        apiKey: getEnvValue(envContent, "WHATSAPP_API_KEY", ""),
        phoneNumber: getEnvValue(envContent, "WHATSAPP_PHONE_NUMBER", ""),
        publicPhoneNumber: getEnvValue(envContent, "NEXT_PUBLIC_WHATSAPP_PHONE_NUMBER", ""),
      },
      collections: {
        maxCollections: parseInt(String(getEnvValue(envContent, "HOMEPAGE_MAX_COLLECTIONS", "8")) || 8),
        cacheTime: getEnvValue(envContent, "COLLECTION_CACHE_TIME", "days"),
      },
      newsletter: {
        service: getEnvValue(envContent, "NEWSLETTER_SERVICE", ""),
        apiKey: getEnvValue(envContent, "NEWSLETTER_API_KEY", ""),
        listId: getEnvValue(envContent, "NEWSLETTER_LIST_ID", ""),
      },
      payment: {
        provider: getEnvValue(envContent, "PAYMENT_PROVIDER", "demo"),
      },
    };

    return NextResponse.json({ success: true, config });
  } catch (error) {
    console.error("Error reading config:", error);
    return NextResponse.json(
      { success: false, error: "Failed to read configuration" },
      { status: 500 }
    );
  }
}

export async function POST(request: NextRequest) {
  try {
    const config: ConfigData = await request.json();
    
    // Generate new .env content
    let envContent = `# LilyaArt Configuration - Generated by Admin Dashboard
# Last updated: ${new Date().toISOString()}

# Shopify Configuration
SHOPIFY_STORE_DOMAIN="${config.shopify.storeDomain}"
SHOPIFY_STOREFRONT_ACCESS_TOKEN="${config.shopify.storefrontAccessToken}"
SHOPIFY_WEBHOOK_SECRET="${config.shopify.webhookSecret}"
SHOPIFY_REVALIDATION_SECRET="${config.shopify.revalidationSecret}"
NEXT_PUBLIC_URL="${config.shopify.publicUrl}"
SHOPIFY_ADMIN_ACCESS_TOKEN="${config.shopify.adminAccessToken}"
SHOPIFY_CLIENT_ID="${config.shopify.clientId}"
SHOPIFY_CLIENT_SECRET="${config.shopify.clientSecret}"

# Site Configuration
COMPANY_NAME="${config.site.companyName}"
SITE_NAME="${config.site.siteName}"

# Notification Configuration
ENABLE_EMAIL_NOTIFICATIONS="${config.notifications.enableEmail}"
ENABLE_WHATSAPP_NOTIFICATIONS="${config.notifications.enableWhatsApp}"
ADMIN_EMAIL="${config.notifications.adminEmail}"
CUSTOM_ORDER_MESSAGE="${config.notifications.customMessage}"

# Email Service Configuration
EMAIL_SERVICE_PROVIDER="${config.emailService.provider}"
EMAIL_SERVICE_API_KEY="${config.emailService.apiKey}"
EMAIL_FROM_EMAIL="${config.emailService.fromEmail}"
EMAIL_FROM_NAME="${config.emailService.fromName}"

# WhatsApp Service Configuration
WHATSAPP_SERVICE_PROVIDER="${config.whatsappService.provider}"
WHATSAPP_API_KEY="${config.whatsappService.apiKey}"
WHATSAPP_PHONE_NUMBER="${config.whatsappService.phoneNumber}"
NEXT_PUBLIC_WHATSAPP_PHONE_NUMBER="${config.whatsappService.publicPhoneNumber}"

# Collections Configuration
HOMEPAGE_MAX_COLLECTIONS=${config.collections.maxCollections}
COLLECTION_CACHE_TIME=${config.collections.cacheTime}

# Newsletter Configuration
NEWSLETTER_SERVICE="${config.newsletter.service}"
NEWSLETTER_API_KEY="${config.newsletter.apiKey}"
NEWSLETTER_LIST_ID="${config.newsletter.listId}"

# Payment Configuration
PAYMENT_PROVIDER="${config.payment.provider}"
`;

    // Write to .env file
    const envPath = path.join(process.cwd(), ".env");
    await writeFile(envPath, envContent, "utf-8");

    // Also create a backup
    const backupPath = path.join(process.cwd(), `.env.backup.${Date.now()}`);
    await writeFile(backupPath, envContent, "utf-8");

    return NextResponse.json({ 
      success: true, 
      message: "Configuration saved successfully",
      backup: backupPath 
    });
  } catch (error) {
    console.error("Error saving config:", error);
    return NextResponse.json(
      { success: false, error: "Failed to save configuration" },
      { status: 500 }
    );
  }
}

function getEnvValue(content: string, key: string, defaultValue: string): string {
  // Handle both quoted and unquoted values
  const regex = new RegExp(`^${key}\\s*=\\s*["']?(.*?)["']?\\s*$`, "m");
  const match = content.match(regex);
  return match && match[1] ? match[1] : defaultValue;
}